### ISSUE TITLE
'JQuery Inspect Middleware' object has no attribute 'request start'

### ISSUE THREAD

**Issue by paulocheque** [dobarkod/django-queryinspect#12]
I received this error only in the first request after I started the `runserver` command. 

    'JQuery Inspect Middleware' object has no attribute 'request start'

Steps to reproduce:

1) Logout
2) Restart the server `./manage.py runserver
3) In the browser: http://localhost:8000/admin (without the final slash)

**Comment by senko** [comment]
Thanks for reporting this @paulocheque.

Which version of Django are you using?

**Comment by paulocheque** [comment]
Django 1.7. I believe there is something related to the redirect `without slash` to `with slash`.

**Comment by orf** [comment]
I'm getting this as well when I have an app that hits a django-rest-framework endpoint. It keeps erroring until I make a request to a non-api page.

**Comment by senko** [comment]
@paulocheque I believe https://github.com/dobarkod/django-queryinspect/pull/13 fixed your particular issue - can you test?

**Comment by paulocheque** [comment]
It is probably the same thing since I am using DRF too. I will close this issue ok? Thanks!
