### ISSUE TITLE
Django 1.8 compatible release missing.

### ISSUE THREAD

**Issue by jaydg** [dobarkod/django-queryinspect#14]
The current release 0.0.4 causes deprecation warnings when used with Django 1.8.
The required changes seem to be present, the only thing missing is a new release.

**Comment by stefan8** [comment]
Bump
Could you release to pypi, please?
This import fix is crucial for django 1.9.

**Comment by senko** [comment]
Hey @stefan8 @jaydg - I've just made a new release (0.10.0) with the Django 1.8 + Django 1.9 support in (also fixed some deprecation warnings for upcoming Django 1.10 changes).

Fixed in 6a71bf7

**Comment by senko** [comment]
Thanks for prodding :-)

**Comment by stefan8** [comment]
great, many thanks :)
